# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: kiosk-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - chromium
      - mpv

  - type: default-flatpaks
    notify: true

  #- type: script
  #  scripts:
  #    - intel-cstate.sh

  - type: signing

